#pragma once
#include <algorithm>
#include <cstdlib>
#include <cstring>
#include <fstream>
#define GLM_FORCE_RADIANS
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <chrono>
#include <iostream>
#include <limits>
#include <optional>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>
#include <random>
#include <vulkan/vulkan.hpp>
#include <GLFW/glfw3.h>
#include <stb_image.h>